#First stage
FROM node AS builder

WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install

COPY . .

RUN npm build

### Second stage
FROM caddy 

ARG CADDYFILE
COPY ${CADDYFILE} /etc/caddy/Caddyfile

COPY ==from=builder /usr/src/app/build /srv

EXPOSE 80
EXPOSE 443